# General playback settings
save-position-on-quit
resume-playback=yes
screenshot-format=png
screenshot-directory=~/Pictures/mpv_screenshots

directory-filter-types=video
# autocreate-playlist=filter
keep-open=no

# Volume settings
volume-max=200
audio-normalize-downmix=yes

vo=gpu-next

# yt-dlp settings
cache=yes
demuxer-cache-wait=yes
cache-secs=240
demuxer-max-bytes=1G
