#!/usr/bin/env bash

menu_args=$(printf '%b' ' Files\n Install\n󰸉 Change Wallpaper\n Record Screen\n󰮞 Remove\n󰣇 Update' | rofi -dmenu -p " Options: " -i -theme-str "window {width: 20em;}")

case "$menu_args" in
*Files)
	rofi -show recursivebrowser -theme-str 'window {width: 42em;} listview {lines: 8;}'
	;;
*Install)
	install_args=$(printf '%b' '󰣇 Pacman\n󰣇 AUR\n TUI' | rofi -dmenu -p "󰛀 Install: " -i -theme-str "window {width: 20em;}")
	case "$install_args" in
	*Pacman)
		~/.local/bin/terminal-floating ~/.local/bin/pkg-install
		;;
	*AUR)
		~/.local/bin/terminal-floating ~/.local/bin/pkg-aur-install
		;;
	*TUI)
		~/.local/bin/terminal-floating ~/.local/bin/tui-install
		;;
	esac
	;;
*Remove)
	remove_args=$(printf '%b' '󰣇 Packages\n TUI' | rofi -dmenu -p " Remove: " -i)
	case "$remove_args" in
	*Packages)
		~/.local/bin/terminal-floating ~/.local/bin/pkg-remove
		;;
	*TUI)
		~/.local/bin/terminal-floating ~/.local/bin/tui-remove
		;;
	esac
	;;

*Change\ Wallpaper)
	~/.local/bin/niriwall
	;;
*Record\ Screen)
	record_args=$(printf '%b' '󰍹 Display\n󰽟 Display + Audio\n󰖠 Webcam + Audio\n󰹑 Region\n󱄄 Region + Audio' | rofi -dmenu -p " Record: " -i -theme-str "window {width: 20em;}")
	case "$record_args" in
	*Display)
		~/.local/bin/screenrecord output
		;;
	*Display\ +\ Audio)
		~/.local/bin/screenrecord output --with-audio
		;;
	*Webcam\ +\ Audio)
		~/.local/bin/screenrecord output --with-webcam --with-audio
		;;
	*Region)
		~/.local/bin/screenrecord region
		;;
	*Region\ +\ Audio)
		~/.local/bin/screenrecord region --with-audio
		;;
	esac
	;;
*Update)
	~/.local/bin/terminal-floating ~/.local/bin/pkg-update
	;;
esac
